### PR TITLE
Nightly

### PR DESCRIPTION
**Pull request by lillithrosepup**
I had already made it for catgen n it was as simple as renaming it so here ya go ! see https://github.com/nimaereth/CatGen/pull/2

already tested and works great

[to test it](https://github.com/ImLvna/clangen_catmaker/actions/runs/4557801966)
image

### CODE REVIEW

**Comment by lillithrosepup** [comment]
oh also i renamed requirments.txt it was annoying /lh

**Comment by lillithrosepup** [comment]
link will be [https://nightly.link/keyraven/clangen_catmaker/build/main](https://nightly.link/keyraven/clangen_catmaker/build/main)
**dont open it until actions have finished the first time or else nightly will cache that theres nothing there and wont update for a bit**

**Comment by lillithrosepup** [comment]
also win32 fails bc it doesnt wanna upload sometimes so you gotta rerun it

**Comment by keyraven** [comment]
Thank you! I'll so sorry I didn't see this until now!

**Pull request merged**
